### PR TITLE
Transparent background logos

### PR DESCRIPTION
**Pull request by opotowsky**
Updates the two logos to use .png images with transparent background so there's no awkward pure-white on off-white issues

### CODE REVIEW

**Comment by ypark234** [comment]
Where does the new UW logo `uw-logo-rectangle-transparent.png` come from?
It seems slightly different from what is available from [UW brand website](https://brand.wisc.edu/print/logos/).

**Comment by opotowsky** [comment]
@ypark234 Thanks so much for catching that! 1. this is a logo I grabbed from the website in ~2014 that I kept on hand. Looks like UW since changed their branded font! 2. I renamed it to match the cnerg logo since I didn't have the original name, but i'll update this with the new logo/its original name

**Comment by ypark234** [comment]
Just out of curiosity: I only see changes in logo filenames in `.tex` and `.sty` file,
but when I look at the `sample-poster.pdf`, the spacings between title, author and affiliation seem to have also changed.
How did this happen and is it intended?

**Comment by opotowsky** [comment]
Good catch! I did not do a side by side as I should have.

Both logos have slightly different aspect ratios than the ones they replaced. However, the .tex and .sty files define these to both be 8cm high, and they fit well within their horizontal limitations of ~30cm, so the different vertical spacing of the name/title is not expected. 

In response to this unexpected behavior:
1. I tweaked this spacing for my own needs recently, so perhaps the default behavior isn't super important
2. I like how the newer spacing looks better, so if the default behavior IS important, I'd vote this way anyway :-)

**Pull request merged**
